rec = {
    'positive_interaction': 'Maintain good eye contact\n'
                            ' Maintaining good eye contact shows you are engaged and actively listening to what'
                            '\n someone is telling you.'
                            '\n However, if you stare too intensely, it can have the opposite effect by making'
                            '\n the other person feel too targeted.'
                            '\n Assess their body language in response to determine if they feel comfortable. '
                            '\n \n Head nod '
                            '\n In addition to showing a speaker that you agree with their message, '
                            '\n nodding your head shows others that you are listening to what they have to say.'
                            '\n When you pair a head nod with a smile, you’re more likely to engage them with '
                            '\n inclusive enthusiasm. '
                            '\n Leaning in while speaking (and listening) The distance you keep between others '
                            '\n is also a nonverbal cue. '
                            '\n While you never want to impose on someone’s personal space, leaning in and '
                            '\n facing their direction when communicating indicates'
                            '\n that you are comfortable with them and interested in the exchange. '
                            '\n \n Minimal facial expressions '
                            '\n If you are trying to avoid showing any type of facial expression, it may be '
                            '\n perceived as you having something to hide.'
                            '\n Limited facial expression can also be interpreted as an intimidation tactic '
                            '\n or disinterest in the conversation.'
                            '\n Similarly, if you keep your eyes on the floor or maintain little to no eye '
                            '\n contact with someone, \n it can indicate that you are uncomfortable, shy or even '
                            '\ndishonest. ',
    'authoritative': 'Hands '
                     '\n Talking with your hands is an easy way to incorporate gestures into your conversation '
                     '\n but be careful not to make it a dance party.'
                     '\n Emphasizing words with your hands can lead you to appear more credible and assured.'
                     '\n \n arms held behind body with hands clasped'
                     '\n As demonstrated by members of the royal family, armed forces officers, teachers, policemen.. '
                     '\n \n finger pointing (in the air)\n  Pointing in the air is generally used to add emphasis, '
                     '\n by a person feeling in authority or power. '
                     '\n \n head tilted downward \n Head tilted downwards towards a person is commonly a signal of '
                     '\n criticism or reprimand or disapproval, usually from a position of authority. '
                     '\n \n palm(s) down \n Where the lower arm moves across the body with palm down this is generally'
                     '\n defiance or firm disagreement. ',
    'appriciation': 'Mirror others '
                    '\n Mirroring others is a way to connect and become more relatable.'
                    '\n When mirroring, consider the jargon the other person uses, '
                    '\n the types of discussions they enjoy and their normal volume for speaking.'
                    '\n Copying their body language is a way to express your similarity and appreciation of someone.',

    'confidence': 'Firm handshake'
                  '\n When you offer someone a firm handshake, it shows your confidence and respect.'
                  '\n If you are the first one to reach out for a handshake, it further expresses your confidence.'
                  '\n Firm does not mean intimidating (or painful), however. '
                  '\n As with most physical communication, you want to be confident and present,'
                  '\n not off-putting or forceful. '
                  '\n \n hand(s) on hip(s)'
                  '\n The person is emphasizing their presence and readiness for action. '
                  '\n Observable in various situations, notably sport and less pronounced poses in social '
                  '\n and work situations. ',
    'calm': 'Relax your body.'
            '\n Maintain the appearance of calm by keeping your hands still and breathing slowly.'
            '\n \n palms down moving up and down, fingers spread'
            '\n Seen often in rowdy meetings the gesture is typically a few inches above the tabletop'
            '\n but is also seen standing up.'
            '\n The action is one of suppressing or holding down a rising pressure.'
            '\n Teachers use this gesture when trying to quiet a class.',
    'excitement': 'Rapid blinking'
                  '\n Your eyes often express a lot about what you or someone else is feeling or thinking. When you '
                  '\n engage with someone, consider their eye movements. While it is normal to blink, rapid blinking '
                  '\n often indicates distress or discomfort with a particular situation. On the other hand, infrequent'
                  '\n blinking may indicate that you are intentionally controlling your blinking to fool those around '
                  '\n you. For example, if you are a part of a poker game, you may attempt to blink less frequently to '
                  '\n not give away your excitement from getting dealt a good hand of cards.',
    'reliability': 'Open palms'
                   '\n Having an open palm implies openness and honesty.'
                   '\n  The idea of “open arms” applies here,'
                   '\n  where you are comforting and accepting of what you are receiving.'
                   '\n Much like being closed off suggests apprehension or guardedness. If you are hearing great ideas,'
                   '\n  receive them openly.'
                   ' \n \n Minimal facial expressions If you are trying to avoid showing any type of facial expression,'
                   ' \n it may be perceived as you having something to hide.'
                   '\n  Limited facial expression can also be interpreted as an intimidation tactic'
                   '\n  or that you aren’t interested in the conversation.'
                   '\n  Similarly, if you keep your eyes on the floor or'
                   '\n  maintain little to no eye contact with someone, '
                   '\n  it can indicate that you are uncomfortable, shy or even dishonest.'
                   ' \n \n Rapid finger tapping or fidgeting'
                   '\n  When you rapidly tap your fingers on a surface or you are constantly fidgeting'
                   ' \n or touching your face, it can show that you are nervous or fearful.'
                   '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
                   '\n When you continuously fidget with your hair '
                   '\n or touch your face repeatedly during a job interview, '
                   '\n  it can even indicate that you are not trustworthy.'
                   '\n \n Hands.'
                   '\n  Talking with your hands is an easy way to incorporate gestures '
                   '\n into your conversation but be careful not to make it a dance party.'
                   ' \n Emphasizing words with your hands can lead you to appear more credible and assured.',
    'happines': 'Upright and open posture '
                '\n Having an upright and open posture means you are keeping the trunk of your body open and free '
                '\n from crossed arms or legs. '
                '\n  This body stance may indicate not only how you are feeling, but also your particular personality.'
                '\n  When you have an open posture, it often signals friendliness and openness.'
                ' \n \n Smile. '
                '\n our brains are affected by the emotions we tell it to feel more often than not.'
                '\n Even if we smile to no one but ourselves, cracking a grin instantly boosts our self-esteem '
                '\n levels--maybe even subliminally reminding us of times that felt better. '
                '\n  When your confidence is lagging, try smiling and see what happens.',
    'insecure': 'Rapid blinking'
                '\n  Your eyes often express a lot about what you or someone else is feeling or thinking. '
                '\n When you engage with someone, consider their eye movements. While it is normal to blink,'
                '\n  rapid blinking often indicates distress or discomfort with a particular situation. '
                '\n On the other hand, infrequent blinking may indicate '
                '\n  that you are intentionally controlling your blinking to fool those around you.'
                '\n  For example, if you are a part of a poker game,'
                '\n you may attempt to blink less frequently to not give away your excitement from getting dealt a '
                '\n good hand of cards. '
                ' \n \n Lip biting or pursed lips '
                '\n If you chew on your lips, it can signal to someone that you are worried about something'
                '\n  or feel insecure in your current environment.'
                '\n  If you purse or tighten your lips, it can indicate distaste or disapproval.'
                '\n  Gripping upper arms, while folded, is effectively self-hugging.'
                '\n  Self-hugging is an attempt to reassure unhappy or unsafe feelings.'
                ' \n \n thumb(s) clenched inside fist(s) '
                '\n As with other signals involving holding or stroking a part of' "one's" 'own body,'
                '\n  this tends to indicate self-comforting.'
                '\n Also, thumbs are potent and flexible tools, so disabling them logically reduces a' "person's" 'readiness for action.',
    'fear': 'Lip biting or pursed lips '
            '\n If you chew on your lips, it can signal to someone that you are worried about something'
            '\n  or feel insecure in your current environment.'
            '\n  If you purse or tighten your lips, it can indicate distaste or disapproval.'
            '\n \n Crossed arms The use of your arms can often convey several nonverbal cues.'
            '\n  For example, when you cross your arms, it shows your defensiveness.'
            '\n  It can also indicate that you are trying to protect yourself from something '
            '\n or that you are closing yourself off from further interaction with another person or a group of people.'
            '\n \n Rapid finger tapping or fidgeting '
            '\n When you rapidly tap your fingers on a surface or you are constantly fidgeting or touching your face,'
            '\n  it can show that you are nervous or fearful. '
            '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
            '\n  When you continuously fidget with your hair or touch your face repeatedly during a job interview,'
            '\n  it can even indicate that you are not trustworthy.',
    'discomfort': 'Rapid blinking'
                  '\n  Your eyes often express a lot about what you or someone else is feeling or thinking. '
                  '\n When you engage with someone, consider their eye movements. While it is normal to blink,'
                  '\n  rapid blinking often indicates distress or discomfort with a particular situation. '
                  '\n On the other hand, infrequent blinking may indicate '
                  '\n  that you are intentionally controlling your blinking to fool those around you.'
                  '\n  For example, if you are a part of a poker game,'
                  '\n you may attempt to blink less frequently to not give away your excitement from getting dealt a '
                  '\n good hand of cards. '
                  '\n Minimal facial expressions '
                  '\n \n If you are trying to avoid showing any type of facial expression, it may be perceived as you '
                  ' \n having something to hide. '
                  '\n  Limited facial expression can also be interpreted as an intimidation tactic or that you aren’t '
                  '\n interested in the conversation. '
                  '\n  Similarly, if you keep your eyes on the floor or maintain little to no eye contact with someone,'
                  '\n  it can indicate that you are uncomfortable, shy or even dishonest.'
                  '\n \n Crossed legs away from a person'
                  '\n Crossing your legs away from a particular individual may indicate dislike or discomfort.'
                  '\n  If you see someone do this to you, it may mean they need some space.'
                  '\n \n cracking knuckles '
                  '\n Usually male. Machismo or habit. Meaning depends on context.'
                  '\n  It is still unknown exactly how the noise is made, '
                  '\n but the notion that the practice leads to arthritis is now generally thought to be nonsense.',
    'anger': 'hand(s) on hip(s)'
             '\n The person is emphasizing their presence and readiness for action. '
             '\n Observable in various situations, notably sport and less pronounced poses in social '
             '\n and work situations. '
             '\n \n Rapid finger tapping or fidgeting'
             '\n  When you rapidly tap your fingers on a surface or you are constantly fidgeting'
             ' \n or touching your face, it can show that you are nervous or fearful.'
             '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
             '\n When you continuously fidget with your hair or touch your face repeatedly during a job interview,'
             '\n  it can even indicate that you are not trustworthy.',
    'shyness':'\n Minimal facial expressions '
                  '\n \n If you are trying to avoid showing any type of facial expression, it may be perceived as you '
                  ' \n having something to hide. '
                  '\n  Limited facial expression can also be interpreted as an intimidation tactic or that you aren’t '
              '\n interested in the conversation. '
                  '\n  Similarly, if you keep your eyes on the floor or maintain little to no eye contact with someone,'
                  '\n  it can indicate that you are uncomfortable, shy or even dishonest.'
    '\n \n Head in hands '
              '\n Placing your head in your hands demonstrates your boredom.'
              '\n  For example, if you place your head in your hand while your manager leads a meeting,'
              '\n it indicates that you are not truly interested in what they have to say.'
              '\n If you place your head in your hands to hide your face, it may indicate that you are upset or '
              '\n ashamed about something. '
}
''''
    

    ,
    'confusion',
    'stubbornness',
    'interest in surroundings
    'Rapid blinking'
                  '\n Your eyes often express a lot about what you or someone else is feeling or thinking.'
                  '\n When you engage with someone, consider their eye movements.'
                  '\n While it is normal to blink, rapid blinking often indicates distress or discomfort'
                  '\n with a particular situation.'
                  '\n On the other hand, infrequent blinking may indicate that you are intentionally controlling your '
                  '\n blinking to fool those around you. '
                  '\n  For example, if you are a part of a poker game,'
                  '\n you may attempt to blink less frequently to not give away your excitement from getting dealt a '
                  'good hand of cards. ',
    
    '''
