rec = {
    'positive interaction': 'Upright and open posture '
                            '\n Having an upright and open posture means you are keeping the trunk of your body open '
                            '\n and free  from crossed arms or legs. '
                            '\n This body stance may indicate not only how you are feeling, but also your particular '
                            '\n personality. When you have an open posture, it often signals friendliness and openness.'
                            '\n \n Head nod '
                            '\n In addition to showing a speaker that you agree with their message, '
                            '\n nodding your head shows others that you are listening to what they have to say.'
                            '\n When you pair a head nod with a smile, you’re more likely to engage them with '
                            '\n inclusive enthusiasm. '
                            '\n \n Leaning in while speaking (and listening)'
                            '\n The distance you keep between others is also a nonverbal cue. '
                            '\n While you never want to impose on someone’s personal space, leaning in and '
                            '\n facing their direction when communicating indicates'
                            '\n that you are comfortable with them and interested in the exchange. '
                            '\n \n Leaning in while speaking (and listening) '
                            '\n The distance you keep between others is also a nonverbal cue. While you never want '
                            '\n to impose on someone’s personal space, leaning in and facing their direction when '
                            '\n communicating indicates that you are comfortable with them and interested in the '
                            '\n exchange. '
                            '\n \n Mirror others'
                            '\n Mirroring others is a way to connect and become more relatable.'
                            '\n When mirroring, consider the jargon the other person uses, '
                            '\n the types of discussions they enjoy and their normal volume for speaking.'
                            '\n Copying their body language is a way to express your similarity and appreciation '
                            '\n of someone. '
    ,
    'authoritative': 'Hands '
                     '\n Talking with your hands is an easy way to incorporate gestures into your conversation '
                     '\n but be careful not to make it a dance party.'
                     '\n Emphasizing words with your hands can lead you to appear more credible and assured.'
                     '\n \n Arms held behind body with hands clasped'
                     '\n As demonstrated by members of the royal family, armed forces officers, teachers, policemen.. '
                     '\n \n Finger pointing (in the air)'
                     '\n  Pointing in the air is generally used to add emphasis, '
                     '\n by a person feeling in authority or power. '
                     '\n \n Head tilted downward '
                     '\n Head tilted downwards towards a person is commonly a signal of '
                     '\n criticism or reprimand or disapproval, usually from a position of authority. '
                     '\n \n Palm(s) down \n Where the lower arm moves across the body with palm down this is generally'
                     '\n defiance or firm disagreement. '
                     '\n \n Steepling Your Fingers'
                     '\n Holding your fingertips together and your palms apart let people know you have authority and '
                     '\n control. Bosses and politicians use this gesture often to show they are in charge.'
                     '\n \n Take up as much space as possible by keeping your shoulders wide and your stance open.'
                     '\n \n Sit straight in your chair (if seated), with your back against the back of the chair, '
                     '\n your shoulders back and facing forward, and your feet flat on the floor. You can also lean '
                     '\n forward slightly in order to nonverbally signal your involvement in the conversation.'
                     '\n Unless occasionally emphasizing a point in your speech,'
                     '\n keep your hands neatly folded in your lap or at your sides during the conversation.',

    'confidence': 'Hand(s) on hip(s)'
                  '\n The person is emphasizing their presence and readiness for action. '
                  '\n Observable in various situations, notably sport and less pronounced poses in social '
                  '\n and work situations. '
                  '\n \n Lean forward'
                  '\n When you are in a conversation, leaning forward indicates interest and attention.'
                  '\n  While it can be tempting to maintain distance if you are socially anxious, doing so conveys '
                  '\n the message that you are disinterested or aloof. '
                  '\n \n  Stand up straight'
                  '\n Do not slouch! Those with social anxiety tend to try and take up as little space as possible, '
                  '\n which can mean sitting slumped over in a protective pose. Straighten your back, pull your '
                  '\n shoulders away from your ears, and uncross your arms and legs. '
                  '\n \n Keep your chin up'
                  '\n Do you look at the ground when you are walking? Is your head always down?'
                  '\n Instead, walk with your head up and your eyes looking forward. It might feel unnatural at first,'
                  '\n but eventually, you will become used to this more confident pose. '
                  '\n \n Hands.'
                  '\n Though it can be tempting to shove your hands in your pockets, particularly if you are worried '
                  '\n about them shaking, doing so makes you look more anxious and less confident.'
                  '\n Keep your hands out of your pockets to look more self-assured. '
                  '\n Be careful about touching your face or your neck; both are indications that you feel anxious, '
                  '\n nervous, or afraid. Confident people do not make these types of movements.',
    'calm': 'Relax your body'
            '\n Maintain the appearance of calm by keeping your hands still and breathing slowly.'
            '\n \n Palms down moving up and down, fingers spread'
            '\n Seen often in rowdy meetings the gesture is typically a few inches above the tabletop'
            '\n but is also seen standing up.'
            '\n The action is one of suppressing or holding down a rising pressure.'
            '\n Teachers use this gesture when trying to quiet a class.'
            '\n \n Relaxed limbs'
            '\n Relaxed limbs hang loosely. They do not twitch and seldom cross one another, unless as a position of '
            '\n comfort. '
            '\n \n Arms '
            '\n Tense arms are rigid and may be held close to the body. They may move in suddenly, a staccato manner. '
            '\n Relaxed arms either hang loosely or move smoothly. '
            '\n If arms cross one another, they hand loosely. Any crossing, of course can indicate some tension. '
            '\n Folding arms may just be comfortable. '
            '\n \n Hands '
            '\n When we are anxious, we often use our hands to touch ourselves, hold ourselves/otherwise show tension.'
            '\n Relaxed hands hang loose or are used to enhance what we are saying. They are generally open and'
            '\n may shape ideas in the air. Gestures are open and gentle, not sudden nor tense. '
            '\n \n Legs'
            '\n Legs when sitting may sit gently on the floor or may be casually flung out. They may move in time to '
            '\n music, with tapping toes. They may be crossed, but are not wound around one another. '
            '\n Note that legs can be a particular sign of hidden tension when the person is controlling the upper '
            '\n body and arms. When they are sitting at a table, what you see may be relaxed, but the legs may be held '
            '\n tense and wrapped.',
    'excitement': 'Rubbing Your Hands Together'
                  '\n Want to show how excited you are about a new project? Just rub your hands together vigorously.'
                  '\n \n Hands'
                  '\n Many people use gestures for emphasis when speaking. This can have some direct benefits, '
                  '\n as researchTrusted Source suggests we tend to answer someone’s question faster if they make '
                  '\n gestures while asking. The more enthusiastic the gesture, the more excitement someone’s likely '
                  '\n feeling. It’s also fairly common for people to gesture toward someone they feel particularly '
                  '\n close to, often without realizing it.'
                  '\n \n Leaning into a conversation or toward someone'
                  '\n typically suggests interest or excitement.'
                  '\n \n Standing up straight, sometimes with hands on hips,'
                  '\n  can suggest excitement, eagerness, and confidence.',
    'reliability': 'Tilt your head'
                   '\n Tilting your head shows a willingness to adopt a more vulnerable position. Whenever we want '
                   '\n to display trust, commitment, approval or interest, we bare our neck to others, We show that we '
                   '\n are ready to listen, without contradiction. '
                   '\n \n Open the palms of your hands'
                   '\n Open palms are a sign of peaceful intentions, It shows that you have nothing to hide, '
                   '\n you’re unarmed and you’re mentally open to what the other person is saying. '
                   '\n People who keep their palms open are also seen as more credible and easily trusted. This '
                   '\n explains why religious leaders show their palms when addressing an audience. '
                   '\n \n Rapid finger tapping or fidgeting'
                   '\n When you rapidly tap your fingers on a surface or you are constantly fidgeting'
                   '\n or touching your face, it can show that you are nervous or fearful.'
                   '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
                   '\n When you continuously fidget with your hair '
                   '\n or touch your face repeatedly during a job interview, '
                   '\n it can even indicate that you are not trustworthy.'
                   '\n \n Hands'
                   '\n Talking with your hands is an easy way to incorporate gestures '
                   '\n into your conversation but be careful not to make it a dance party.'
                   '\n Emphasizing words with your hands can lead you to appear more credible and assured.'
                   '\n \n Mirroring other people’s body language can create a sense of closeness and acceptance, '
                   '\n one similar to friendship.'
                   '\n The next time you meet new people, try matching the position of their arms, the timbre of '
                   '\n their voice or even their facial expressions. After a short time, your conversation partner will'
                   '\n subconsciously experience that they feel comfortable with you. This happens because they see '
                   '\n their own reflection mirrored in you.',
    'happiness': 'Upright and open posture '
                 '\n Having an upright and open posture means you are keeping the trunk of your body open and free '
                 '\n from crossed arms or legs. '
                 '\n This body stance may indicate not only how you are feeling, but also your particular personality.'
                 '\n When you have an open posture, it often signals friendliness and openness.'
                 '\n \n Gripping upper arms, while folded, is effectively self-hugging.'
                 '\n Self-hugging is an attempt to reassure unhappy or unsafe feelings.'
                 '\n \n Straight back'
                 '\n When a person becomes happy, their backs become straighter, and their posture becomes more '
                 '\n upright. Sadness, on the other hand, results in a curved back. '
                 '\n \n Confident posture'
                 '\n Happiness is strongly connected to confidence. When a person feels happy, they feel better about '
                 '\n themselves, and so they are more likely to have any of the common confidence body language '
                 '\n postures.',
    'insecurity': 'Gripping upper arms, while folded, is effectively self-hugging.'
                  '\n Self-hugging is an attempt to reassure unhappy or unsafe feelings.'
                  '\n \n Thumb(s) clenched inside fist(s) '
                  '\n As with other signals involving holding or stroking a part of' "one's" 'own body,'
                  '\n this tends to indicate self-comforting.'
                  '\n Also, thumbs are potent and flexible tools, so disabling them logically reduces a' "person's"
                  '\n readiness for action.'
                  '\n \n Arms Crossed Across The Chest '
                  '\n Your arms and legs are perhaps one of the first types of nonverbal communication that people '
                  '\n notice when they see you. You can use them for positive body language or negative body language. '
                  '\n Sitting or standing with your arms crossed across your chest is nearly always seen as defensive '
                  '\n body language.'
                  '\n Universally, people view a person that has crossed arms as insecure,'
                  '\n annoyed, or closed off. When you do it, you are closed off and disengaged.'
                  '\n  You may appear angry or stubborn. If you see someone with their arms and legs crossed for a '
                  '\n long period of time, remember that it could indicate that the temperature where you are is too '
                  '\n cold. It could also mean they are tired or simply supporting their shoulders in an armless chair.'
                  '\n \n Hunched shoulders.'
                  '\n nervous habits how to overcome your insecurities, You tend to hunch your shoulders (pulling '
                  '\n them forward and in) when you’re stressed and are attempting to make your body small. '
                  '\n Remind yourself to take slow, deep breaths as you speak. The deeper the breath, the more it '
                  '\n will force your torso and shoulders to open',
    'fear': 'Posture is a very important element in the body language of fear.'
            '\n In general, your muscles tense up when you’re scared.'
            '\n The first thing that happens is that you begin to'
            '\n slouch (your body does this to occupy less space).'
            '\n This is an expression of the desire to protect yourself and take refuge in your own body. '
            '\n Insecurity, nervousness, and anxiety are manifestations of fear.'
            '\n Those three states tend to come to the surface when you make quick and sudden movements.'
            '\n A person who isn’t able to stay still isn’t calm.'
            '\n When fear is overpowering you, you’re more likely to make more clumsy or sudden movements. '
            '\n Similarly, it’s very common for a scared person to cross their arms. This is a defense signal.'
            '\n The person does this to create a barrier that protects them and keeps them away'
            '\n from the external  world. '
            '\n This barrier can also be a sign of rejection of the outside world. '
            '\n \n Crossed arms'
            '\n The use of your arms can often convey several nonverbal cues.'
            '\n For example, when you cross your arms, it shows your defensiveness.'
            '\n It can also indicate that you are trying to protect yourself from something or that you are closing'
            '\n yourself off from further interaction with another person or a group of people.'
            '\n \n Rapid finger tapping or fidgeting '
            '\n When you rapidly tap your fingers on a surface or you are constantly fidgeting or touching your face,'
            '\n it can show that you are nervous or fearful. '
            '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
            '\n When you continuously fidget with your hair or touch your face repeatedly during a job interview,'
            '\n it can even indicate that you are not trustworthy.'
            '\n \n Gripping upper arms, while folded, is effectively self-hugging.'
            '\n Self-hugging is an attempt to reassure unhappy or unsafe feelings.',
    'discomfort': 'Neck Touching or Neck Rubbing'
                  '\n Your neck is home to many nerve endings that, when rubbed, will lower your heart rate and '
                  '\n comfort you. When people are uncomfortable, they will unconsciously touch their necks so that '
                  '\n these nerves will activate and help to calm them.Rubbing or stroking on the front or back of the '
                  '\n neck is the most common kind of neck touching, but if the person is wearing a necklace or a '
                  '\n necktie, they might fiddle with that also. '
                  '\n \n Face Touching or Face Rubbing'
                  '\n There are also nerve endings in your face, so some people will rub their face to comfort '
                  '\n themselves. Look for rubbing the forehead, rubbing the eyes, playing with the hair, '
                  '\n rubbing lips---all of these are behaviors people use to calm themselves down. People will also '
                  '\n sometimes puff out their cheeks and exhale. '
                  '\n \n Leg Rubbing'
                  '\n This is where a seated person puts their hands (or hand) palm-down on their legs and slides it '
                  '\n towards their knees. Picture someone wiping off sweaty palms on their pants and you have got the '
                  '\n idea. '
                  '\n \n Feet Pointed Away'
                  '\n Feet are extremely powerful indicators of how  someone is actually feeling.  If someones feet '
                  '\n are pointed away from their conversation partner, '
                  '\n '  "that's" 'often a signal that' "they'd" 'rather exit the conversation. Of course, '
                  '\n this only applies if the person could comfortably and naturally point their feet at their '
                  '\n partner---if you are sitting next to each other on an airplane, this does not apply because it '
                  '\n would be very difficult for them to point their feet at you. But if you are standing facing one '
                  '\n another, and you see their feet start pointing towards the door, you might want to graciously '
                  '\n bring the conversation to a close. '
                  '\n \n Crossed legs away from a person'
                  '\n Crossing your legs away from a particular individual may indicate dislike or discomfort.'
                  '\n If you see someone do this to you, it may mean they need some space.',
    'anger': 'The posture of an angry person usually implies he is ready for a fight.'
             '\n He might' "'square off'" 'against you, as if sizing you up. Open displays, such as moving the arms '
             '\n away from the torso, might serve as a dare for you to throw the first strike. Even if the anger is not'
             '\n directed at you, you can look at the chest area and assess the' "person's" 'breathing pattern. Shallow'
             '\n or rapid breathing indicate strong emotions, so watch the rise and fall of the chest. '
             '\n The extremities, particularly the hands, will often reveal tension. For example, clenched fists often '
             '\n reveal frustration or a readiness to fight. The person might begin pacing the room, or she might '
             '\n combine yelling with rigid finger points in the direction of whatever is angering her.'
             '\n In cases of extreme anger, the person might use sudden movements to throw, slam or kick nearby '
             '\n objects. '
             '\n In this last case, leave the room if safety is a concern. '
             '\n \n Hand(s) on hip(s)'
             '\n The person is emphasizing their presence and readiness for action. '
             '\n Observable in various situations, notably sport and less pronounced poses in social '
             '\n and work situations. '
             '\n \n Rapid finger tapping or fidgeting'
             '\n When you rapidly tap your fingers on a surface or you are constantly fidgeting'
             '\n or touching your face, it can show that you are nervous or fearful.'
             '\n Also, these body movements may indicate that you are bored, impatient or frustrated.'
             '\n When you continuously fidget with your hair or touch your face repeatedly during a job interview,'
             '\n it can even indicate that you are not trustworthy.'
             '\n \n Standing With Your Hands Clasped Behind Your Back '
             '\n Take a position with your hands clasped behind your back, and others may read this as anger, '
             '\n apprehension, or frustration. It may feel like a nice, casual pose, but in reality, it can make '
             '\n others uncomfortable and wary of you.',
    'shyness': 'Head in hands '
               '\n Placing your head in your hands demonstrates your boredom.'
               '\n For example, if you place your head in your hand while your manager leads a meeting,'
               '\n it indicates that you are not truly interested in what they have to say.'
               '\n If you place your head in your hands to hide your face, it may indicate that you are upset or '
               '\n ashamed about something. '
               '\n \n Fidgeting'
               '\n This is the main thing shy people do when they’re really nervous.'
               '\n First of all, you have to realize when you are doing it, and stop. Plant your feet in one spot, '
               '\n relax your arms at your sides, and take your hands off of your face. You have to learn to relax in '
               '\n social situations. The best way to do this is to act like you are already relaxed on the outside. '
               '\n \n Nervous habits'
               '\n You can’t fake body language. What you think on the inside will broadcast on the outside.'
               '\n From now on, start from the inside. Try to feel relaxed and calm on the inside, instead of trying '
               '\n to hide your anxiety and nervousness. '
               '\n There are a whole lot of insecure habits shy people have that they can not really control. The '
               '\n only way to stop doing them is to not feel insecure in the first place. This type of improvement '
               '\n usually takes time, but it is what you should be ultimately aiming for.'
               '\n \n Staring at the floor'
               '\n Whatever you do, don’t look down. A lot of shy people get into the habit of looking at the ground. '
               '\n They “watch out” for obstacles in their way. Try not looking down for a day. At first you may be '
               '\n scared of tripping, but soon you’ll get used to it. It’s all about breaking the habit.'
               '\n Keep your chin up, ALWAYS, and your posture straight but relaxed.',
    'confusion': 'Shoulder shrugs '
                 '\n The shoulder shrug is a universal gesture that expresses confusion. It has three main parts.'
                 '\n Exposed palms show nothing is concealed in the hands,'
                 '\n hunched shoulders protect the throat from attack, and raised brows serve as a universal,'
                 '\n submissive greeting. '
                 '\n \n -Head tilting to the side '
                 '\n \n - Hands touching the lips, mouth, face '
                 '\n \n - Glance darting around, head turning, as if looking for answers'
                 '\n \n - Opening the mouth but not speaking,or opening and closing the mouth several times before '
                 '\n forming words '
                 '\n \n - Wilting posture '
                 '\n \n - Scratching at the cheek, rubbing one’s chin '
                 '\n \n - Tapping a fist against the lips lightly while thinking '
                 '\n \n Shaking head '
                 '\n when someone cocks their head, people take that body language to mean confusion.'
                 '\n This is not always the case. In areas where violence is prevalent, such as prison or UFC fights,'
                 '\n people will get into each others’ faces and cock their heads as a challenge. ',
    'stubbornness': 'Hands on hips '
                    '\n While standing with your hands on your hips may show others that you feel in control, '
                    '\n it can also indicate your aggression. Keep in mind that while you may feel powerful, '
                    '\n this body movement has the potential to intimidate others and make them feel uncomfortable. '
                    '\n \n  Figure Four Leg Clamp '
                    '\n In this posture, the person locks one leg over the other and places both his hands on to the '
                    '\n \n Raised leg'
                    '\n This gesture shows that the person is totally disinterested in us and is stubborn in attitude.'
                    '\n This gesture also signifies that the person is tough minded and does not respect '
                    '\n others’ opinion. He is just concerned about his own opinions. '
                    '\n \n Arms Crossed Across The Chest '
                    '\n Your arms and legs are perhaps one of the first types of nonverbal communication that people '
                    '\n notice when they see you. You can use them for positive/negative body language.'
                    '\n Sitting or standing with your arms crossed across your chest is nearly always seen as defensive'
                    '\n body language.'
                    '\n Universally, people view a person that has crossed arms as insecure,'
                    '\n annoyed, or closed off. When you do it, you are closed off and disengaged.'
                    '\n  You may appear angry or stubborn. If you see someone with their arms and legs crossed for a '
                    '\n long period of time, remember that it could indicate that the temperature where you are is too '
                    '\n cold. It could also mean they are tired or simply supporting their shoulders in an armless '
                    '\n chair.'
                    '\n \n Figure Four Leg Clamp'
                    '\n In this posture, the person locks one leg over the other and places both his hands'
                    '\n on to the raised leg.'
                    '\n This gesture shows that the person is totally disinterested in us and is stubborn in attitude.'
                    '\n This gesture also signifies that the person is tough '
                    '\n minded and does not respect others’ opinion.'
                    '\n He is just concerned about his own opinions. '
    ,

}
